# exception handling in python
#=========finally executed for sure==========
# x= 30
# try:
#     print(x)
# except:
#     print("Exception occurred")
    
# finally:
#     print("finally executed")



#==========in-bult check errors by name==========
# try:
#     num1/num2

# except NameError:
#     print("name error occurred")
# except ZeroDivisionError:
#     print("can not divided by zero")

#=========find errors=============
# try:
#     print(name)
    
# except Exception as z:
#     print(z)



